MODEL:
    PRETRAIN: True
    PRETRAIN_POSITION: True
    PRETRAIN_SIZE: True
    ENCODER: 
        NAME: 'Rel2Box'
        REL_GT: False
        VOCAB_SIZE: 34
        OBJ_CLASSES_SIZE: 300
        HIDDEN_SIZE: 256
        NUM_LAYERS: 8
        ATTN_HEADS: 8
        DROPOUT: 0.1
        ENABLE_NOISE: False
        NOISE_SIZE: 64
        SIZE_INPUT: False
        PARENT_ID: True
        FIT_ROOT: False
    DECODER:
        HEAD_TYPE: 'GMM' # 'GMM', 'Linear'
        BOX_LOSS: 'GMM' # for 'GMM' -> 'PDF', for 'Linear' -> 'Reg'
        SCHEDULE_SAMPLE: False
        TWO_PATH: False
        GLOBAL_FEATURE: True
        GREEDY: True
        XY_TEMP: 1.
        WH_TEMP: 1.
        SIZE_INPUT: False
        FIT_ROOT: True
    REFINE:
        REFINE: False
        HEAD_TYPE: 'Linear'
        BOX_LOSS: 'Reg'
        X_Softmax: True
    TRAINER: 
        NAME: 'PretrainTrainer'
    LOSS:
        WEIGHT_VOCAB_LOSS: 1.8
        WEIGHT_TYPE_LOSS: 0.1
        WEIGHT_COARSE_BOX_LOSS: 0.1
        WEIGHT_REFINE_BOX_LOSS: 1.
        WEIGHT_POSITION_LOSS: 0.5
        WEIGHT_SIZE_LOSS: 0.5
        KD_LOSS: False
        TOPK: 5
DATASETS:
    NAME: 'clay'
    COCO_ADDON: False
    DATA_DIR_PATH: './data/clay/'
DATALOADER:
    SMART_SAMPLING: True
    SHUFFLE: True
    VAL_SPLIT: 0.1
    NUM_WORKER: 0
SOLVER:
    EPOCHS: 50
    BATCH_SIZE: 32
    PRETRAIN_WEIGHT: '' #'./saved/pretrained_vg_msdn_AB_v0/checkpoint_50.pth'
    ENCODER:
        LR_SCHEDULER: 'BertScheduler'   # BaseScheduler, ChrisScheduler, BertScheduler
        WARMUP_RATIO: 0.1
        HOLD_RATIO: 0.001
        DECAY_RATIO: 0.9
        MAX_LR: 0.0004
        MIN_LR: 0.00000001
    BBOX_HEAD:
        LR_SCHEDULER: 'BertScheduler'   # BaseScheduler, ChrisScheduler, BertScheduler
        WARMUP_RATIO: 0.1
        HOLD_RATIO: 0.001
        DECAY_RATIO: 0.9
        MAX_LR: 0.0004
        MIN_LR: 0.00000001
OUTPUT:
    NUM_STEPS_SHOW_LOSS: 100
    OUTPUT_DIR: 'experiments/clay_pretrain_grid'
TEST:
    MODE: 'model'
    TEST_IS_MASK: False
    LAYOUT_MODE: 'experiments/clay_seq2seq_grid/test_1/layout'
    RANDOM: False
    SAMPLE_IDX: -1
    OUTPUT_DIR: 'experiments/clay_pretrain_grid/test_1/'
